# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c763ff308c314b36fa924b43e5dc5805568d3533743b064e874c3853f997025a47f956d768bdaef9c148fc266c0aa3949b498ac65378e5359953341ae7a43fb9
  database:
    :host: localhost
    :name: Cor-notes_development
    :username: cornell
    :password: <%= ENV["CORNELL_PASSWORD"] %>

test:
  secret_key_base: f325a1c1efdc726f679404d882141cdd4d6bf535a9dd5f2d87e14bba28f69f3f581f7dea4b2965d3072e38f7296433f1e5e23efe5929c394ed7d768daac6f1db
  database:
    :host: localhost
    :name: Cor-notes_test
    :username: cornell
    :password: <%= ENV["CORNELL_PASSWORD"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["CORNELL_KEY_BASE"] %>
  database:
    :name: cor-notes_production
    :host: localhost
    :username: cornell
    :password: <%= ENV["CORNELL_PASSWORD"] %>